- hosts: "{{ servidor }}"
  gather_facts: no
  vars:
    ansible_user: svc-ansiblehom@<domain>
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
- name: procurando arquivo
  replace:
    path: "{{ arquivo }}"
    regexp: "{{ oldpattern }}"
    replace: "{{ newpattern }}"


