# Reiniciando o serviço do Appdynamics Agent coordinator
- hosts: "{{ servidor }}"
  gather_facts: no
  vars:
    ansible_user: svc-ansibleprd@<domain>
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore

  tasks:
  - name: Verificando versão
    win_shell: 'restart-service "AppDynamics.Agent.Coordinator_Service"'
    register: result_shell
  - debug: var=result_shell