# Pegando uso de memória do WebApp
- hosts: "{{ servidor }}"
  gather_facts: no
  vars:
    ansible_user: svc-ansibleprd@<domain>
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    process: "'w3wp.exe'"

  tasks:
  - name: Verificando versão
    win_shell: 'gwmi win32_process -Filter "name = "{{ process }}"" | sort-object -descending WS | Select-Object WS, Commandline | Select-String -Pattern "(?<=-ap.).*(?=.-v)" -AllMatches | % {$_.Matches} | % {$_.Value}'
    register: result_shell
   
  - debug: var=result_shell

  
